//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesiones
    {
        public int IdSesion { get; set; }
        public bool lSession { get; set; }
        public DateTime DteInicio { get; set; }
        public DateTime DteFin { get; set; }
        public int IdUser { get; set; }
    }
}
