//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IdUser { get; set; }
        public string UserName { get; set; }
        public string Contrasena { get; set; }
        public string Nombre { get; set; }
        public string SegNombre { get; set; }
        public string ApellidoPat { get; set; }
        public string ApellidoMat { get; set; }
    }
}
